"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var blockchain_1 = require("./blockchain");
var blockchain = new blockchain_1.Blockchain();
var alice = new blockchain_1.Wallet(blockchain);
var bob = new blockchain_1.Wallet(blockchain);
var miner = new blockchain_1.Wallet(blockchain);
alice.createTransaction(bob.adress, 70);
bob.createTransaction(alice.adress, 50);
console.log();
console.log(alice.adress + " - " + blockchain.balanceOfAdress(alice.adress));
console.log(bob.adress + " - " + blockchain.balanceOfAdress(bob.adress));
console.log(miner.adress + " - " + blockchain.balanceOfAdress(miner.adress));
console.log();
blockchain.minePendingTransactions(miner.adress);
console.log();
console.log(alice.adress + " - " + blockchain.balanceOfAdress(alice.adress));
console.log(bob.adress + " - " + blockchain.balanceOfAdress(bob.adress));
console.log(miner.adress + " - " + blockchain.balanceOfAdress(miner.adress));
console.log();
miner.createTransaction(alice.adress, 30);
bob.createTransaction(alice.adress, 60);
blockchain.minePendingTransactions(miner.adress);
console.log();
console.log(alice.adress + " - " + blockchain.balanceOfAdress(alice.adress));
console.log(bob.adress + " - " + blockchain.balanceOfAdress(bob.adress));
console.log(miner.adress + " - " + blockchain.balanceOfAdress(miner.adress));
console.log();
console.log();
console.log('Blockchain valid: ' + blockchain.isChainValid);
console.log(JSON.stringify(blockchain.chain, null, 2));
console.log();
console.log('tampering chain...');
blockchain.chain[1].transactions[0].amount = 200;
console.log('Blockchain valid: ' + blockchain.isChainValid);
